spring:
  application:
    name: gateway-micro-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          # 开启以服务id的形式去获取注册中心上的地址
          enabled: true
      # 路由策略
      routes:
        # 转发百度
        - id: test-gateway-micro-service
          # 转发地址
          uri: https://www.baidu.com
          filters:
            - StripPrefix=1 #当访问localhost:80/test/**时，就会转化为https://www.baidu.com/test/**转发，但是这是个无效地址，所以要通过StripPrefix=1去除uri的第一个前缀改为https://www.baidu.com/**进行转发
          # 断言（匹配规则）
          predicates:
            - Path=/test/**
#            - PrefixPath=/lbs #此参数是增加前缀
        # 转发到本地8098端口
        - id: user-gateway-service
          uri: http://localhost:8098
          filters:
            - StripPrefix=1
          predicates:
            - Path=/local/learn/user/**
        # 转发到注册中心服务
        - id: user-gateway-micro-service
          # lb为基于lb负载均衡形式转发
          uri: lb://user-micro-service
          # 断言（匹配规则）
          # 通过http://localhost:80/learn/user/**访问到服务user-micro-service，再通过predicates断言来判断user-micro-service服务下是否有/learn/user/**接口地址，
          # 若有，则predicates为true，则访问成功 ，若为false，则访问失败。因此不再暴露真实端口，统一换成网关80
          predicates:
            - Path=/learn/user/**
server:
  port: 80