spring:
  profiles:
    include:
      - config-learn
      - config-web
      - config-datasource
      - config-personal
      - config-thymeleaf
      - config-env
      - config-log
      - config-arthas