# 遗留问题为什么这样配置不行
#spring:
#  profiles:
#    include:
#      - config-learn
#      - config-web
#      - config-datasource
#      - env

spring:
  application:
    name: springboot-learn
  datasource:
    # 使用docker-compose时，mysql:3306 这里不能写localhost:3306，应该写mysql:3306，mysql对应的是配置文件中服务名称
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:springboot_learn}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: ${WEB_PORT:8090}
  servlet:
    # 设置springboot项目访问路径
    context-path: /learn
