spring:
  application:
    name: dubbo-user-micro-service-provider
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:springboot_learn}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: ${WEB_PORT:8097}
  servlet:
    context-path: /learn
dubbo:
  application:
    name: dubbo-user-service
  protocol:
    # 传输协议
    name: dubbo
    # dubbo的服务端口号
    port: 20891
  #注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181