### 本项目配置
learn:
  template:
    template-path: D:\ideaProject\myself\java-learn\springboot\src\main\resources\template_file
### spring配置
spring:
  application:
    name: springboot-learn
  mvc:
    async:
      request-timeout: 60000
# 缓存查询
cache_query:
  enable: ${CACHE_QUERY_ENABLE:false}
  level: ${CACHE_QUERY_LEVEL:NONE}
# 多线程计算
multi-thread-calc:
  pool:
    core-size: ${MULTI_THREAD_CALC_POOL_CORE_SIZE:3}