# arthas 仅在controller集成
spring:
  arthas:
    # 默认关闭, arthas开启后，根据下方的arthas打开对应的端口
    enabled: ${ARTHAS_ENABLE:false}
arthas:
  # 如果配置 arthas.telnetPort为 -1 ，则不监听 telnet端口。arthas.httpPort类似。
  # 如果配置 arthas.telnetPort为 0 ，则随机telnet端口，在~/logs/arthas/arthas.log里可以找到具体端口日志。arthas.httpPort类似。
  # telnetPort打开后本机可以使用 "telnet localhost ${arthas.telnetPort}"进入arthas控制台, httpPort打开后本机可以使用浏览器"http://localhost:${arthas.telnetPort}"进入arthas控制台
  # telnet端口默认为3658
  telnetPort: ${ARTHAS_PORT:3658}
  # 监听http端口
  httpPort: -1
  # 127.0.0.1只能本地访问，0.0.0.0则可网络访问，但是存在安全问题
  ip: 127.0.0.1
  appName: ${spring.application.name}
  # 默认情况下，会生成随机ID，如果 arthas agent配置了 appName，则生成的agentId会带上appName的前缀。
  agent-id: hsehdfsfghhwertyfad
  # tunnel-server地址, 注释掉则不会连接tunnel-server
  # tunnel-server: ws://localhost:7777/ws
